### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by shirazmatas** [shirazmatas/Projinda#2]
Exception in thread "main" java.lang.IllegalStateException: No match available
	at java.base/java.util.regex.Matcher.end(Matcher.java:522)
	at ICalParser.parse(ICalParser.java:42)
	at Main.main(Main.java:8)

Chatgpt säger: regex.matcher inte matchar men raden innan så är det if, varför?

**Comment by shirazmatas** [comment]
Solved
